language:
  no_perm: '§cYou don''t have permission to do this!'
  unload_self: 'You can''t unload the functioning plugin.'
  loading: 'Start loading '
  unloading: 'Unloading '
  reloading: 'Start reloading '
  reload_failed: '§eFailed to reload plugin '
  unload_failed: '§cFailed to unload '
  plugin_not_found: '§eNo such plugin named '
  file_not_found: '§eNo such file named '
  already_loaded: 'Plugin %0% have already been loaded!'
  unload_success: 'Plugin %0% unloaded successfully!'
  load_success: 'Plugin %0% loaded successfully!'
  invalid_plugin: '§cInvalid plugin!'
  listing_plugins: 'Listing all loaded plugins:'
